// cabral/navbar/navbar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-navbar',
  template: `
    <header>
      <nav>
        <div class="logo">SORA</div>
        <ul class="nav-links">
          <li><a href="#home">Home</a></li>
          <li><a href="#collection">Collection</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          <ng-container *ngIf="!isLoggedIn">
            <li><button class="auth-btn" (click)="authClick.emit()">Login</button></li>
            <li><button class="auth-btn" (click)="authClick.emit()">Register</button></li>
          </ng-container>
        </ul>
        <div>
          <div class="cart-icon" (click)="cartClick.emit()">
            <i class="fas fa-shopping-cart"></i>
            <span id="cart-count">{{cartCount}}</span>
          </div>
          <div class="profile-icon-nav" (click)="profileClick.emit()">
            <i class="fas fa-user-circle"></i>
          </div>
        </div>
      </nav>
    </header>
  `
})
export class NavbarComponent {
  @Input() cartCount: number = 0;
  @Input() isLoggedIn: boolean = false;
  @Output() cartClick = new EventEmitter();
  @Output() authClick = new EventEmitter();
  @Output() profileClick = new EventEmitter();
}

// cabral/components/Navbar.jsx
import React from 'react';

function Navbar({ cartCount, isLoggedIn, onCartClick, onAuthClick, onProfileClick }) {
  return (
    <header>
      <nav>
        <div className="logo">SORA</div>
        <ul className="nav-links">
          <li><a href="#home">Home</a></li>
          <li><a href="#collection">Collection</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          {!isLoggedIn && (
            <>
              <li><button className="auth-btn" onClick={onAuthClick}>Login</button></li>
              <li><button className="auth-btn" onClick={onAuthClick}>Register</button></li>
            </>
          )}
        </ul>
        <div>
          <div className="cart-icon" onClick={onCartClick}>
            <i className="fas fa-shopping-cart"></i>
            <span id="cart-count">{cartCount}</span>
          </div>
          <div className="profile-icon-nav" onClick={onProfileClick}>
            <i className="fas fa-user-circle"></i>
          </div>
        </div>
      </nav>
    </header>
  );
}

export default Navbar;
